# Generated by Django 5.2.8 on 2025-12-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_admin_remove_item_name_item_item_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_name',
            new_name='staff_id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='admin_email',
        ),
    ]
