# Generated by Django 5.2.8 on 2025-12-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_admin_name_admin_staff_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, unique=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemReservation',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline_time', models.DateField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.user')),
            ],
        ),
    ]
