# Generated by Django 5.2.8 on 2025-12-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_user_useritemreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_amount', models.IntegerField()),
                ('request_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.user')),
            ],
        ),
    ]
