# Generated by Django 5.2.8 on 2025-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_requestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='time_requested',
            field=models.TimeField(auto_now_add=True, default='12:00:00'),
            preserve_default=False,
        ),
    ]
