# Generated by Django 5.2.8 on 2025-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_requestitem_time_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='time_requested',
            field=models.TimeField(default=None, max_length=8),
        ),
    ]
