# Generated by Django 5.2.8 on 2025-12-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_requestitem_time_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
