# Generated by Django 5.2.8 on 2025-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_requestitem_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='time_requested',
            field=models.TextField(blank=True, null=True),
        ),
    ]
