# Generated by Django 5.2.8 on 2025-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_requestitem_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
