# Generated by Django 5.2.8 on 2025-12-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_requestitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.admin'),
        ),
    ]
