# Generated by Django 5.2.8 on 2025-12-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_requestitem_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestVenue',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('time_requested', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('admin_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.admin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.user')),
            ],
        ),
    ]
