# Generated by Django 5.2.8 on 2025-12-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_requestvenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.admin')),
            ],
        ),
    ]
