# Generated by Django 5.2.8 on 2025-12-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_material_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestvenue',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestvenue',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fine_reason', models.CharField(default='Overdue return', max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Unpaid', max_length=20)),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.requestitem')),
                ('request_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.requestvenue')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.user')),
            ],
        ),
    ]
